name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Copy everything into ./dist for publishing
      - name: Prepare static site folder
        run: |
          mkdir -p dist
          shopt -s extglob dotglob
          cp -R !(dist|.git|.github) dist || true

      # Avoid Jekyll processing (important if you ever have _folders)
      - name: Add .nojekyll
        run: |
          touch dist/.nojekyll

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
